// <auto-generated />
using System;
using CuidaDor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuidaDor.Infrastructure.Migrations
{
    [DbContext(typeof(CuidaDorDbContext))]
    [Migration("20251120121724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuidaDor.Domain.Entities.AccessibilityPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FontScale")
                        .HasColumnType("float");

                    b.Property<bool>("HighContrast")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("VoiceReading")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccessibilityPreferences");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.ConsentLgpd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ConsentLgpds");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.GeneralFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeneralFeeling")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GeneralFeedbacks");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.PainAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LimitsPhysicalActivities")
                        .HasColumnType("bit");

                    b.Property<int>("LocalizedPain")
                        .HasColumnType("int");

                    b.Property<int>("MoodToday")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PainWorseWithMovement")
                        .HasColumnType("bit");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("UsesNonDrugPainRelief")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesPainMedication")
                        .HasColumnType("bit");

                    b.Property<int>("UsualPain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PainAssessments");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.ReliefTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReliefTechniques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Respiração 4-7-8",
                            ShortDescription = "Respiração • Ansiedade e sono",
                            WarningText = "Pode dar leve tontura no início"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Respiração profunda",
                            ShortDescription = "Respiração • Reduz tensão e dor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alongamento de mãos",
                            ShortDescription = "Alongamentos • Rigidez matinal",
                            WarningText = "Pare se houver dor forte"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Relaxamento muscular progressivo",
                            ShortDescription = "Relaxamento • Tensão corporal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toque calmante",
                            ShortDescription = "Relaxamento • Conforto imediato"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Calor morno local",
                            ShortDescription = "Termoterapia • Rigidez e desconforto",
                            WarningText = "Evite pele lesionada; teste a temperatura"
                        });
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.TechniqueSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReliefTechniqueId")
                        .HasColumnType("int");

                    b.Property<int>("ResultFeeling")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReliefTechniqueId");

                    b.HasIndex("UserId");

                    b.ToTable("TechniqueSessions");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.TechniqueStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ReliefTechniqueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReliefTechniqueId");

                    b.ToTable("TechniqueSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Inspire pelo nariz contando até 4.",
                            Order = 1,
                            ReliefTechniqueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Segure o ar contando até 7.",
                            Order = 2,
                            ReliefTechniqueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Expire pela boca contando até 8.",
                            Order = 3,
                            ReliefTechniqueId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Repita por 4 ciclos completos.",
                            Order = 4,
                            ReliefTechniqueId = 1
                        });
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.UserComorbidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserComorbidities");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.AccessibilityPreference", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.User", "User")
                        .WithOne("AccessibilityPreference")
                        .HasForeignKey("CuidaDor.Domain.Entities.AccessibilityPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.ConsentLgpd", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.User", "User")
                        .WithOne("ConsentLgpd")
                        .HasForeignKey("CuidaDor.Domain.Entities.ConsentLgpd", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.GeneralFeedback", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.User", "User")
                        .WithMany("GeneralFeedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.PainAssessment", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.User", "User")
                        .WithMany("PainAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.TechniqueSession", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.ReliefTechnique", "ReliefTechnique")
                        .WithMany("Sessions")
                        .HasForeignKey("ReliefTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuidaDor.Domain.Entities.User", "User")
                        .WithMany("TechniqueSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReliefTechnique");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.TechniqueStep", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.ReliefTechnique", "ReliefTechnique")
                        .WithMany("Steps")
                        .HasForeignKey("ReliefTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReliefTechnique");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.UserComorbidity", b =>
                {
                    b.HasOne("CuidaDor.Domain.Entities.User", "User")
                        .WithMany("Comorbidities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.ReliefTechnique", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CuidaDor.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessibilityPreference");

                    b.Navigation("Comorbidities");

                    b.Navigation("ConsentLgpd");

                    b.Navigation("GeneralFeedbacks");

                    b.Navigation("PainAssessments");

                    b.Navigation("TechniqueSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
